### ISSUE TITLE
Breaking change of nuxt.rc-13: project build stopped working

### ISSUE THREAD

**Issue by digitalcortex** [d3xter-dev/sitemap-module-nuxt-3#12]
After updating nuxt to rc-13 project build stopped working.

> ERROR  Cannot read properties of undefined (reading 'etag')                                                11:31:24
> 
>   at setDefaultSitemapOptions (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:180:39)
>   at registerSitemap (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:337:13)
>   at registerSitemaps (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:333:5)
>   at node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:413:7
>   at Array.forEach (<anonymous>)
>   at setup (node_modules/@funken-studio/sitemap-nuxt-3/dist/module.mjs:412:13)
>   at async Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:642:5)
>   at async installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:427:3)
>   at async initNuxt (node_modules/nuxt/dist/index.mjs:1787:7)
>   at async loadNuxt (node_modules/nuxt/dist/index.mjs:1819:5)
>   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:737:19)
>   at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:34:18)
>   at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

**Comment by re2005** [comment]
For now if you add to your `nuxt.config`

```ts
    render: {
        etag: {
            weak: false
        }
    }
```

It will work just fine.

**Comment by digitalcortex** [comment]
> For now if you add to your `nuxt.config`
> 
> ```ts
>     render: {
>         etag: {
>             weak: false
>         }
>     }
> ```
> 
> It will work just fine.

Thank you for sharing the workaround! What could be the potential effect on the website if we set etag weak option to false?

**Comment by re2005** [comment]
Check:
https://nuxtjs.org/docs/configuration-glossary/configuration-render/#etag

I hope @reolat @d3xter-dev or one of the maintainers here can make the fix:
https://github.com/funkenstudio/sitemap-module-nuxt-3/blob/experimental/src/options.ts#L26

Nuxt rc.13 may have changed the `etag` api.

**Comment by ltroya-as** [comment]
@digitalcortex @d3xter-dev is it generation the sitemap for you? Because it is not working for me in the RC13.

I started simple:

`nuxt.config.js`
```
modules: ['@nuxtjs/tailwindcss', '@funken-studio/sitemap-nuxt-3'],

  // @ts-ignore
  sitemap: {
    hostname: 'https://source.benchmarkminerals.com',
    cacheTime: 1,
    routes: ['/', '/login'],
    defaults: {
      changefreq: 'daily',
      priority: 1,
      lastmod: new Date().toISOString(),
    },
  },
```

I will appreciate any hint!

**Comment by digitalcortex** [comment]
Sitemap generation seems to work fine. I have a small map made just of one link, you can check it here: https://trillex.io/sitemap.xml

**Comment by vincekruger** [comment]
Solved.
The `render` options works, however, I have this problem now :(

```The 'render' does not exist in type 'NuxtConfig'.ts(2345)```

**Comment by re2005** [comment]
Nuxt3 is out!

When fix <3

Cheers

**Comment by d3xter-dev** [comment]
Hopefully, I can find some time tomorrow / later this evening! 
Sorry for letting you guys wait!

**Comment by vincekruger** [comment]
Open Source Life. :)

**Comment by Anoesj** [comment]
@d3xter-dev It seems you've commited some fixes yesterday, but the version wasn't bumped, so I can't try them out.. Is it not ready yet or did you simply forget to bump its version? :innocent:

**Comment by d3xter-dev** [comment]
Hey! Yes, I worked on it yesterday evening. I still need to do a bit more testing :)  But there will be a new version asap

**Comment by d3xter-dev** [comment]
I hope that issue is fixed now :)  Let me know if not.
