### ISSUE TITLE
404.html and 200.html pages in sitemap.xml

### ISSUE THREAD

**Issue by tschortsch** [d3xter-dev/sitemap-module-nuxt-3#15]
When running the `nuxt generate` command the `404.html` and `200.html` pages get added to the sitemap. This is happending since version `4.0.3` of the module. Is this the desired behavior? Maybe I'm wrong but I don't think those two pages should get indexed by a search engine right?

**Comment by mertgonul** [comment]
You can exclude these pages by specifying them in the nuxt.config.ts file.

`
sitemap: {
    exclude: ['/200.html', '/404.html'],
  }
 `

**Comment by tschortsch** [comment]
thanks for the hint! 👌🏻

**Comment by IgorHalfeld** [comment]
ty @mertgonul 

this is useful for add admin routes as well
