### ISSUE TITLE
Dynamic routes are cached ?

### ISSUE THREAD

**Issue by GreenmeisterDavid** [d3xter-dev/sitemap-module-nuxt-3#18]
When following the example to get dynamic routes to work (custom backend), it seems like the sitemap.xml is being cached instead of being fetched live on every load (no matter the generateOnBuild setting). The sitemap is properly populated, but changes from my API aren't coming through.

**Comment by d3xter-dev** [comment]
You can set the time for  which the routes are cached by defining 
`
sitemap: { 
    ...
    cacheTime: 1,
    ....
}
`
