### ISSUE TITLE
“Generating sitemaps” message printed numerous times, sitemap incomplete

### ISSUE THREAD

**Issue by Anoesj** [d3xter-dev/sitemap-module-nuxt-3#7]
When running `pnpm nuxt generate`, the following message is repeated for every generated html file
```
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
```

Let me give an example of a `sitemap.xml` and the `pnpm nuxt generate` output in a very common Nuxt 3 setup.

#### Contents of `pages/` directory:
- `users/`
  - `index.vue`
    - Fetches `id` and `name` of all users from a backend and renders links to their profile pages. In this case, it receives one user with id `1` and renders a link to `/users/1`. The Nuxt crawler should therefore prerender `.output/public/users/1/index.html`.
  - `[id].vue`
    - Fetches data of user `[id]` from a backend and renders a user profile page.
- `index.vue`
  - Fetches `id`, `route` and `title` of every page from a backend and renders links to their respective pages. Because this route lists links to every available page, the Nuxt crawler should therefore prerender all of those routes.
- `[...slug].vue`
  - Fetches data of page with matching route from a backend.

#### Output of `pnpm nuxt generate`:
```
ℹ Client built in 4779ms
ℹ Building server...
✔ Server built in 1329ms
✔ Generated public .output/public
ℹ Initializing prerenderer
ℹ Prerendering 2 initial routes with crawler
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /users (333ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ / (46ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /users/1 (49ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /about (49ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /topics (99ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /topics/environment (48ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /topics/environment/nitrogen-crisis (42ms) 
ℹ Generating sitemaps
✔ Generated /../.output/public/sitemap.xml
  ├─ /topics/politics (34ms) 
✔ You can now deploy .output/public to any static hosting!
```

Firstly, this output is confusing, because it feels like this output suggests that the `sitemap.xml` file is overwritten many times.

Secondly, one would think that all the routes that were prerendered by Nuxt would appear in the generated `sitemap.xml`, but only the static/non-dynamic routes were actually added to `sitemap.xml`, namely:
- `/` (from `/pages/index.vue`)
- and `/users` (from `/pages/users/index.vue`)

Could you reply to both of these issues and clear up if this is the expected behavior?

Thank you!

**Comment by d3xter-dev** [comment]
I tried a few things, the current version fixes the spamming of "Generating sitemaps", it now only generates it once. 

EDIT: Will release a new version today which will add the pre-rendered routes.

**Comment by Anoesj** [comment]
Sounds great, thanks so much!

**Comment by d3xter-dev** [comment]
Just released a new Version

**Comment by Anoesj** [comment]
Works great, thank you! 🥳
